### ISSUE TITLE
it says that arid sand is not present

### ISSUE THREAD

**Issue by okmoonicorn** [team-abnormals/atmospheric#105]
<img width="1440" alt="Screenshot 2021-04-03 at 5 09 23 PM" src="https://user-images.githubusercontent.com/78662963/113492744-64653f80-949f-11eb-9e62-78838885b94e.png">

**Comment by bageldotjpg** [comment]
1. Use 1.16.5
2. If that doesn't fix it, make sure your mods are up to date
3. If that still doesn't fix it, send your `latest.log` and reopen this issue
