### ISSUE TITLE
Rainforest is in the end

### ISSUE THREAD

**Issue by GoldGamer207** [team-abnormals/atmospheric#116]
I am using multiple mods on 1.16.4, and the end islands have turned into a rainforest, i don't know why, but if there is something that could fix it, it would be really good, here are some photos
![2021-05-03_13 19 10](https://user-images.githubusercontent.com/83666713/117048384-e9cb5200-ace0-11eb-8975-1d82ceba2095.png)
![2021-05-03_20 24 55](https://user-images.githubusercontent.com/83666713/117048400-ee900600-ace0-11eb-8bce-320f27f038a2.png) i can submit the mods if needed.

**Comment by bageldotjpg** [comment]
Stop using 1.16.4, make sure you are on latest forge and mod versions for 1.16.5.
This can't be undone unless you have a backup but you can prevent it from continuing to happen
