### ISSUE TITLE
[1.16.5] Atmospheric Sapling Growth causes client desync on servers

### ISSUE THREAD

**Issue by NielsPilgaard** [team-abnormals/atmospheric#118]
Relayed from https://github.com/NillerMedDild/Enigmatica6/issues/2137

atmospheric-1.16.5-3.1.0

> On my server, when one places a grimwood sapling and applies bone meal, the tree becomes a set of ghost blocks for everyone in the area. This doesn't happen in singleplayer but happens consistently in multiplayer. This does not happen with other trees. Just ones from Atmospheric.
> By ghost block I mean the tree exists server-side but does not get synced with the clients. As a result, I cannot see the blocks or interact with them. Rejoining the server will make the tree visible and interactable again.

**Comment by NillerMedDild** [comment]
I've been informed that this does not happen with Atmospheric and dependencies only.

**Comment by NillerMedDild** [comment]
Update: This happens for all Atmospheric saplings
