### ISSUE TITLE
What’s this?

### ISSUE THREAD

**Issue by Feriixu** [team-abnormals/atmospheric#125]
Hi, GitHub recommended me this repo but there is no readme.

**Comment by bageldotjpg** [comment]
It's a Minecraft mod

**Comment by Feriixu** [comment]
Thanks, I know that much already by just looking at the commits. What does it do? Is there a spigotmc page?

**Comment by bageldotjpg** [comment]
https://www.curseforge.com/minecraft/mc-mods/atmospheric
