### ISSUE TITLE
barrel cactus now growing

### ISSUE THREAD

**Issue by frakier** [team-abnormals/atmospheric#134]
Valhelsia+3-3.4.8
Forge 36.2.22
Minecraft 1.16.5
Atmospheric 3.1.1

Barrel Cactus does not grow and I have them on Arid Sand. Bone meal works though.

**Comment by thelegitdolt** [comment]
intended  i think

**Comment by frakier** [comment]
They grew before... literally just quit working from between 3.1.0 and 3.1.1

**Comment by fivelol** [comment]
This is intended behaviour as disclosed in the 3.1.1 changelog. 

There is a way to auto farm barrel cactus planned for a future update, but that'll be on 1.18+.
