### ISSUE TITLE
AloeVeraTallBlock, AloeVeraBlock, BarrelCactusBlock, and PassionVineBlock have an inaccessible crop age field (Mod Compat)

### ISSUE THREAD

**Issue by HyDefier** [team-abnormals/atmospheric#138]
Atmospheric currently uses an IntegerProperty for AGE that cannot be symbolically accessed by other mods. You can inherit CropBlock and make AGE accesible in getAgeProperty() so other mods can access your crops' age in their code.

**Comment by bageldotjpg** [comment]
They are intentionally not crop blocks due to how they are designed, it would cause unintended results and issues. The age property *is* accessible still, and even if it wasn't public it can be accessed.
