### ISSUE TITLE
Dune biomes crash the player

### ISSUE THREAD

**Issue by Shepelo2** [team-abnormals/atmospheric#144]
When I was going to a dunes biome, I ended up crashing. I don't even have to be in the biome to crash, I can get close and it'll crash. This happened three times. The first time was when I teleported to one, one when I flew into one, then one where I walked into it while looking at the ground.

**Comment by Lin-Ain** [comment]
Yes, I met the same problem. Using command like /locatebiome or getting close to the dunes would lead to strange situations. Sometimes the game crashed and shutdown directly, but more commonly the graphic in game became black with no sounds. Pressing ESC could not show the menu. Closing the game also had no reaction so I used task manager to end the game.

**Comment by ClephLeSDF** [comment]
Imagine not using the right beta :trollface: 
![image](https://user-images.githubusercontent.com/16508989/189250899-7c4ec3d4-dd4d-41ea-a784-ce95abeff66d.png)

**Comment by bageldotjpg** [comment]
Fixed indev
