### ISSUE TITLE
oak shrubs spawning on top of other tree

### ISSUE THREAD

**Issue by ClephLeSDF** [team-abnormals/atmospheric#145]
Last beta, seems to happen only inside of sparse rainforest biome
![2022-09-08_20 09 58](https://user-images.githubusercontent.com/16508989/189245838-e3fc3e2f-42bb-4543-a46c-96e06e3a86b1.png)
![2022-09-08_20 09 50](https://user-images.githubusercontent.com/16508989/189245845-ce3fc44d-3db3-4e50-acac-62fbe5819527.png)
![2022-09-08_16 38 40](https://user-images.githubusercontent.com/16508989/189245847-cd13fb68-1a8a-44c6-8afe-f68d3be04ba5.png)

**Comment by bageldotjpg** [comment]
Fixed indev
