### ISSUE TITLE
Fast grafics Flowering Morado Leaves

### ISSUE THREAD

**Issue by OYPyd** [team-abnormals/atmospheric#161]
When I switch to fast graphics leaves turn black
![2023-01-30_15 00 25](https://user-images.githubusercontent.com/123962723/215499482-4324b911-6a45-4457-92af-9e6cb3193f13.png)
I tried it without the other mods and issue persisted

**Comment by bageldotjpg** [comment]
Duplicate of #137, not really fixable though
