### ISSUE TITLE
World generation crashes with terraincognita

### ISSUE THREAD

**Issue by sauphle** [team-abnormals/atmospheric#164]
Playing with the mod "TerraIncognita" crashes the game when generating and playing a world. 
Something about the terraincognita:lush_plains being incompatible with atmospheric:sparse_rainforest_basin

I've disabled terra and atmospheric separately and they only work apart

My game was in pirate speak so I hope that doesn't mess with anything.

[Crash Report.txt](https://github.com/team-abnormals/atmospheric/files/10550408/Crash.Report.txt)

Edit: Minecraft version 1.18, forge version 40.2.1

**Comment by Sagragoth** [comment]
Can confirm, version 1.18, forge version 40.2.0.  Looks like #160 may be the same issue.
