### ISSUE TITLE
[1.19.2] Frogs have the wrong color variant

### ISSUE THREAD

**Issue by thelegitdolt** [team-abnormals/atmospheric#166]
![Screen_Shot_2023-02-01_at_11 14 04_PM](https://user-images.githubusercontent.com/50085439/216688920-81b59b3a-ba65-4ad9-b5c1-ada863918fe7.png)

**Comment by thelegitdolt** [comment]
only in dunes. rainforests are fine

**Comment by bageldotjpg** [comment]
Fixed in 9afdcceaf6589fa01bf9798165bd2f8ac78b473e
