### ISSUE TITLE
Rainforest Trees generating in the water

### ISSUE THREAD

**Issue by Trixdoesthings** [team-abnormals/atmospheric#196]
The rosewood and morado trees are generating in the water.

![2023-06-14_15 17 32](https://github.com/team-abnormals/atmospheric/assets/136550605/9d9e7227-bfc1-41c2-96d6-d53723f911ef)

**Comment by Trixdoesthings** [comment]
It's really bad too

![2023-06-14_15 21 40](https://github.com/team-abnormals/atmospheric/assets/136550605/0e21239e-d879-49bf-b3e0-1940454be4ad)

**Comment by ebo2022** [comment]
This is intentional generation for the Rainforest basin
