### ISSUE TITLE
Crash on fresh world 5.1.0 Beta 1

### ISSUE THREAD

**Issue by zerotheliger** [team-abnormals/atmospheric#217]
Not much to explain in this instance brand new world loading new chunks got this crash and continues to crash the second i load in.

[crash-2024-01-02_21.39.20-server.txt](https://github.com/team-abnormals/atmospheric/files/13815329/crash-2024-01-02_21.39.20-server.txt)

**Comment by vivagabe** [comment]
Same issue. Looks like it has something to do with Dragon Roots. Hopefully a fix soon.
