### ISSUE TITLE
1.19.2  server crash

### ISSUE THREAD

**Issue by mightyjaffa12** [team-abnormals/atmospheric#220]
https://pastebin.com/LbfzbHnE

**Comment by ChiefLogan3010** [comment]
I'm also experiencing this crash wbenever a player gets near a biome with passion fruit vines.

Versions used:
Minecraft 1.19.2
Forge 43.3.8
Blueprint 6.2.0
Atmospheric 5.1.0

Crash log:
https://gist.github.com/ChiefLogan3010/5f0e85ed10173e684e540e3c7437c63d

**Comment by kitovoi111** [comment]
crassh
[crash-2024-03-02_19.01.51-server.txt](https://github.com/team-abnormals/atmospheric/files/14469998/crash-2024-03-02_19.01.51-server.txt)

**Comment by Awesomespore** [comment]
Same here, server crashed while we were exploring, I see passionfruit vine generation blamed in the log

**Comment by bageldotjpg** [comment]
Whoops! Will be fixed in a patch soon
