### ISSUE TITLE
Tall Aloe Vera Bug/Crash

### ISSUE THREAD

**Issue by Fooshcookie** [team-abnormals/atmospheric#78]
Grettings! 

I'm not entirely sure if this is on your end or not, however it seems to be related to the Dunes tall_aloe_vera. It may be a conflict, as I have a giant mod-pack and may not even be on your end. (My apologies if it isn't.) I shall be linking the logs and the crash report both below, as I do not know how to decipher these types of things. 

I will keep an eye out, to provide any extra information required!

Crash Report: https://pastebin.com/earftnyP (I did this after I realized I could just attach the file. Hopefully it's not an issue.)
Latest Log: [latest.log](https://github.com/team-abnormals/atmospheric/files/5768380/latest.log)

Thanks!

**Comment by bageldotjpg** [comment]
This is a bug with BetterWeather, I believe they are working on fix soon
