### ISSUE TITLE
yucca trees in badlands

### ISSUE THREAD

**Issue by Omega58** [team-abnormals/atmospheric#79]
before saying that i shouldn't be doing this,yes,i am aware that i will never be unbanned from the discord,and i totally accept that 

anyway let's get to the issue

it appears yucca trees generate in badlands, precisely wooded ones 
i am using other mods at the same time,those being : enhanced mushrooms,savage and ravage and better badlands

if it's a feature,please let me know in a reply to this

**Comment by bageldotjpg** [comment]
this is intentional
