### ISSUE TITLE
Yucca Trees don't generate in modded Desert, Savanna and Badlands biomes

### ISSUE THREAD

**Issue by Brun333rp** [team-abnormals/atmospheric#88]
They only generate in Vanilla biomes and Dunes

**Comment by bageldotjpg** [comment]
intended

**Comment by Brun333rp** [comment]
why it's intended?

**Comment by bageldotjpg** [comment]
that's just how they're designed, they're trees meant for the dunes only but as a rare bonus they can show up in vanilla deserts, they're not meant to be in other biomes

**Comment by Brun333rp** [comment]
ok then, that's reasonable. but they generate too frequently in wooded badlands, is that intended?
